from DeepBuilder import layer, util, activation
from architecture import layer_temp

InceptionV2_Stem = (
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [7, 7, -1, 64], 'stride_size':[1, 2, 2, 1], 'padding':'SAME', 'name': 'stem_1_conv'}},
    {'method': layer.max_pool, 'kwargs': {'kernel_size': [1, 3, 3, 1], 'stride_size': [1, 2, 2, 1], 'padding': 'SAME', 'name': 'stem_2_maxpool'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 64], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'stem_3_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [3, 3, -1, 192], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'stem_4_conv'}},
    {'method': layer.max_pool, 'kwargs': {'kernel_size': [1, 3, 3, 1], 'stride_size': [1, 2, 2, 1], 'padding': 'SAME', 'name': 'stem_5_maxpool'}},
)

# InceptionV2_Stem = (
#     {'method': layer.conv_2d, 'kwargs': {'kernel_size': [3, 3, -1, 32], 'stride_size':[1, 2, 2, 1], 'padding':'VALID', 'name': 'stem_1_conv'}},
#     {'method': layer.conv_2d, 'kwargs': {'kernel_size': [3, 3, -1, 32], 'stride_size':[1, 1, 1, 1], 'padding':'VALID', 'name': 'stem_2_conv'}},
#     {'method': layer.conv_2d, 'kwargs': {'kernel_size': [3, 3, -1, 64], 'stride_size':[1, 1, 1, 1], 'padding':'SAME', 'name': 'stem_3_conv'}},
#     {'method': layer.max_pool, 'kwargs': {'kernel_size': [1, 3, 3, 1], 'stride_size': [1, 2, 2, 1], 'padding': 'VALID', 'name': 'stem_4_maxpool'}},
#     {'method': layer.conv_2d, 'kwargs': {'kernel_size': [3, 3, -1, 80], 'stride_size': [1, 1, 1, 1], 'padding': 'VALID', 'name': 'stem_5_conv'}},
#     {'method': layer.conv_2d, 'kwargs': {'kernel_size': [3, 3, -1, 192], 'stride_size': [1, 2, 2, 1], 'padding': 'VALID', 'name': 'stem_6_conv'}},
#     {'method': layer.conv_2d, 'kwargs': {'kernel_size': [3, 3, -1, 288], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'stem_7_conv'}},
# )

InceptionV2_ModuleA = (
    {'method': util.AppendInputs, },
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleA_input']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 64], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleA_a_1_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleA_input']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 48], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleA_a_2_1_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [5, 5, -1, 64], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleA_a_2_2_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleA_input']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 64], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleA_a_3_1_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [3, 3, -1, 96], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleA_a_3_2_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [3, 3, -1, 96], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleA_a_3_3_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleA_input']}},
    {'method': layer_temp.avg_pool, 'kwargs': {'kernel_size': [1, 3, 3, 1], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleA_a_4_1_avgpool'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 32], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleA_a_4_2_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleA_a_1_conv', 'moduleA_a_2_2_conv', 'moduleA_a_3_3_conv', 'moduleA_a_4_2_conv']}},
    {'method': activation.Concatenate, 'kwargs': {'name': 'ModuleA_a_concat'}},

    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleA_a_concat']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 64], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleA_b_1_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleA_a_concat']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 48], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleA_b_2_1_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [5, 5, -1, 64], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleA_b_2_2_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleA_a_concat']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 64], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleA_b_3_1_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [3, 3, -1, 96], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleA_b_3_2_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [3, 3, -1, 96], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleA_b_3_3_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleA_a_concat']}},
    {'method': layer_temp.avg_pool, 'kwargs': {'kernel_size': [1, 3, 3, 1], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleA_b_4_1_avgpool'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 64], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleA_b_4_2_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleA_b_1_conv', 'moduleA_b_2_2_conv', 'moduleA_b_3_3_conv', 'moduleA_b_4_2_conv']}},
    {'method': activation.Concatenate, 'kwargs': {'name': 'ModuleA_b_concat'}},

    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleA_b_concat']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 64], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleA_c_1_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleA_b_concat']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 48], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleA_c_2_1_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [5, 5, -1, 64], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleA_c_2_2_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleA_b_concat']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 64], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleA_c_3_1_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [3, 3, -1, 96], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleA_c_3_2_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [3, 3, -1, 96], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleA_c_3_3_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleA_b_concat']}},
    {'method': layer_temp.avg_pool, 'kwargs': {'kernel_size': [1, 3, 3, 1], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleA_c_4_1_avgpool'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 64], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleA_c_4_2_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleA_c_1_conv', 'moduleA_c_2_2_conv', 'moduleA_c_3_3_conv', 'moduleA_c_4_2_conv']}},
    {'method': activation.Concatenate, 'kwargs': {'name': 'ModuleA_c_concat'}},
)

InceptionV2_ModuleB = (
    {'method': util.AppendInputs, },
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleB_input']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [3, 3, -1, 384], 'stride_size': [1, 2, 2, 1], 'padding': 'VALID', 'name': 'moduleB_a_1_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleB_input']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 64], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_a_2_1_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [3, 3, -1, 96], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_a_2_2_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [3, 3, -1, 96], 'stride_size': [1, 2, 2, 1], 'padding': 'VALID', 'name': 'moduleB_a_2_3_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleB_input']}},
    {'method': layer.max_pool, 'kwargs': {'kernel_size': [1, 3, 3, 1], 'stride_size': [1, 2, 2, 1], 'padding': 'VALID', 'name': 'moduleB_a_3_maxpool'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleB_a_1_conv', 'moduleB_a_2_3_conv', 'moduleB_a_3_maxpool']}},
    {'method': activation.Concatenate, 'kwargs': {'name': 'ModuleB_a_concat'}},

    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleB_a_concat']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 192], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_b_1_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleB_a_concat']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 128], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_b_2_1_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 7, -1, 128], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_b_2_2_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [7, 1, -1, 192], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_b_2_3_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleB_a_concat']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 128], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_b_3_1_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 7, -1, 128], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_b_3_2_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [7, 1, -1, 128], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_b_3_3_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 7, -1, 128], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_b_3_4_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [7, 1, -1, 192], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_b_3_5_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleB_a_concat']}},
    {'method': layer_temp.avg_pool, 'kwargs': {'kernel_size': [1, 3, 3, 1], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_b_4_1_avgpool'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 192], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_b_4_2_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleB_b_1_conv', 'moduleB_b_2_3_conv', 'moduleB_b_3_5_conv', 'moduleB_b_4_2_conv']}},
    {'method': activation.Concatenate, 'kwargs': {'name': 'ModuleB_b_concat'}},

    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleB_b_concat']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 192], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_c_1_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleB_b_concat']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 128], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_c_2_1_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 7, -1, 128], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_c_2_2_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [7, 1, -1, 192], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_c_2_3_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleB_b_concat']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 128], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_c_3_1_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 7, -1, 128], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_c_3_2_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [7, 1, -1, 128], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_c_3_3_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 7, -1, 128], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_c_3_4_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [7, 1, -1, 192], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_c_3_5_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleB_b_concat']}},
    {'method': layer_temp.avg_pool, 'kwargs': {'kernel_size': [1, 3, 3, 1], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_c_4_1_avgpool'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 192], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_c_4_2_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleB_c_1_conv', 'moduleB_c_2_3_conv', 'moduleB_c_3_5_conv', 'moduleB_c_4_2_conv']}},
    {'method': activation.Concatenate, 'kwargs': {'name': 'ModuleB_c_concat'}},

    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleB_c_concat']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 192], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_d_1_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleB_c_concat']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 128], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_d_2_1_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 7, -1, 128], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_d_2_2_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [7, 1, -1, 192], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_d_2_3_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleB_c_concat']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 128], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_d_3_1_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 7, -1, 128], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_d_3_2_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [7, 1, -1, 128], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_d_3_3_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 7, -1, 128], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_d_3_4_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [7, 1, -1, 192], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_d_3_5_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleB_c_concat']}},
    {'method': layer_temp.avg_pool, 'kwargs': {'kernel_size': [1, 3, 3, 1], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_d_4_1_avgpool'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 192], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_d_4_2_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleB_d_1_conv', 'moduleB_d_2_3_conv', 'moduleB_d_3_5_conv', 'moduleB_d_4_2_conv']}},
    {'method': activation.Concatenate, 'kwargs': {'name': 'ModuleB_d_concat'}},

    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleB_d_concat']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 192], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_e_1_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleB_d_concat']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 128], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_e_2_1_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 7, -1, 128], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_e_2_2_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [7, 1, -1, 192], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_e_2_3_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleB_d_concat']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 128], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_e_3_1_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 7, -1, 128], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_e_3_2_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [7, 1, -1, 128], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_e_3_3_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 7, -1, 128], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_e_3_4_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [7, 1, -1, 192], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_e_3_5_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleB_d_concat']}},
    {'method': layer_temp.avg_pool, 'kwargs': {'kernel_size': [1, 3, 3, 1], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_e_4_1_avgpool'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 192], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleB_e_4_2_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleB_e_1_conv', 'moduleB_e_2_3_conv', 'moduleB_e_3_5_conv', 'moduleB_e_4_2_conv']}},
    {'method': activation.Concatenate, 'kwargs': {'name': 'ModuleB_e_concat'}},
)

InceptionV2_ModuleC = (
    {'method': util.AppendInputs, },
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleC_input']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 192], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleC_a_1_1_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [3, 3, -1, 320], 'stride_size': [1, 2, 2, 1], 'padding': 'VALID', 'name': 'moduleC_a_1_2_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleC_input']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 192], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleC_a_2_1_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 7, -1, 192], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleC_a_2_2_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [7, 1, -1, 192], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleC_a_2_3_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [3, 3, -1, 192], 'stride_size': [1, 2, 2, 1], 'padding': 'VALID', 'name': 'moduleC_a_2_4_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleC_input']}},
    {'method': layer.max_pool, 'kwargs': {'kernel_size': [1, 3, 3, 1], 'stride_size': [1, 2, 2, 1], 'padding': 'VALID', 'name': 'moduleC_a_3_maxpool'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleC_a_1_2_conv', 'moduleC_a_2_4_conv', 'moduleC_a_3_maxpool']}},
    {'method': activation.Concatenate, 'kwargs': {'name': 'ModuleC_a_concat'}},

    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleC_a_concat']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 320], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleC_b_1_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleC_a_concat']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 384], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleC_b_2_1_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleC_b_2_1_conv']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 3, -1, 384], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleC_b_2_1_1_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleC_b_2_1_conv']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [3, 1, -1, 384], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleC_b_2_1_2_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleC_b_2_1_1_conv', 'moduleC_b_2_1_2_conv']}},
    {'method': activation.Concatenate, 'kwargs': {'name': 'moduleC_b_2_3_concat'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleC_a_concat']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 448], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleC_b_3_1_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [3, 3, -1, 384], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleC_b_3_2_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleC_b_3_2_conv']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 3, -1, 384], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleC_b_3_3_1_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleC_b_3_2_conv']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [3, 1, -1, 384], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleC_b_3_3_2_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleC_b_3_3_1_conv', 'moduleC_b_3_3_2_conv']}},
    {'method': activation.Concatenate, 'kwargs': {'name': 'moduleC_b_3_4_concat'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleC_a_concat']}},
    {'method': layer_temp.avg_pool, 'kwargs': {'kernel_size': [1, 3, 3, 1], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleC_b_4_1_avgpool'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 192], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleC_b_4_2_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleC_b_1_conv', 'moduleC_b_2_3_concat', 'moduleC_b_3_4_concat', 'moduleC_b_4_2_conv']}},
    {'method': activation.Concatenate, 'kwargs': {'name': 'ModuleC_b_concat'}},

    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleC_b_concat']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 320], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleC_c_1_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleC_b_concat']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 384], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleC_c_2_1_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleC_c_2_1_conv']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 3, -1, 384], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleC_c_2_1_1_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleC_c_2_1_conv']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [3, 1, -1, 384], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleC_c_2_1_2_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleC_c_2_1_1_conv', 'moduleC_c_2_1_2_conv']}},
    {'method': activation.Concatenate, 'kwargs': {'name': 'moduleC_c_2_3_concat'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleC_b_concat']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 448], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleC_c_3_1_conv'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [3, 3, -1, 384], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleC_c_3_2_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleC_c_3_2_conv']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 3, -1, 384], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleC_c_3_3_1_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleC_c_3_2_conv']}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [3, 1, -1, 384], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleC_c_3_3_2_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleC_c_3_3_1_conv', 'moduleC_c_3_3_2_conv']}},
    {'method': activation.Concatenate, 'kwargs': {'name': 'moduleC_c_3_4_concat'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['ModuleC_b_concat']}},
    {'method': layer_temp.avg_pool, 'kwargs': {'kernel_size': [1, 3, 3, 1], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleC_c_4_1_avgpool'}},
    {'method': layer.conv_2d, 'kwargs': {'kernel_size': [1, 1, -1, 192], 'stride_size': [1, 1, 1, 1], 'padding': 'SAME', 'name': 'moduleC_c_4_2_conv'}},
    {'method': util.LayerSelector, 'kwargs': {'names': ['moduleC_c_1_conv', 'moduleC_c_2_3_concat', 'moduleC_c_3_4_concat', 'moduleC_c_4_2_conv']}},
    {'method': activation.Concatenate, 'kwargs': {'name': 'moduleC_c_concat'}},
)